MvcEksiSözlük/MvcEksiSözlük/Controllers/AuthorizationController.cs
using BusinnesLayer.Concrete;
using DataAcessesLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcEksiSözlük.Controllers
{
    public class AuthorizationController : Controller
    {
        // GET: Authorization
        AdminManager Am = new AdminManager(new EFAdminDal());
        public ActionResult Index()
        {
            var adminvalues = Am.GetList();
            return View(adminvalues);
        }
        [HttpGet]
        public ActionResult AddAdmin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAdmin(Admin p)
        {
            Am.AdminAdd(p);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteAdmin(int id)
        {
            var adminvalues = Am.GetById(id);
            Am.Delete(adminvalues);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult AdminUpdate(int id)
        {
            var adminvalues = Am.GetById(id);
            return View(adminvalues);
        }
        [HttpPost]
        public ActionResult AdminUpdate(Admin p)
        {
            Am.Update(p);
            return RedirectToAction("Index");
        }
    }
}

MvcEksiSözlük/MvcEksiSözlük/Views/Authorization/AddAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "AddAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>Yeni Admin Ekleme Sayfası</h3>
<br />
@using (Html.BeginForm("AddAdmin", "Authorization", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Admin Kullanıcı Adı:")
    @Html.TextBoxFor(x => x.AdminUsername, new { @class = "form-control" })
    <br />
    @Html.Label("Şifre Giriniz")
    @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
    <br />
    @Html.Label("Role Giriniz")
    @Html.TextBoxFor(x => x.AdminRole, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</div>
}

MvcEksiSözlük/MvcEksiSözlük/Views/Authorization/AdminUpdate.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "AdminUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Kategori Güncelleme sayfası</h2>
@using (Html.BeginForm("AdminUpdate", "Authorization", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.AdminID)
        <br />
        @Html.Label("Admin Kullanıcı Adı")
        @Html.TextBoxFor(x => x.AdminUsername, new { @class = "form-control" })
        <br />
        @Html.Label("Şifre")
        @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
        <br />
        @Html.Label("Role")
        @Html.TextBoxFor(x => x.AdminRole, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

MvcEksiSözlük/MvcEksiSözlük/Views/Authorization/Index.cshtml
@using EntityLayer.Concrete
@model List<Admin>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kullanıcı Mail</th>
        <th>Yetki</th>
        <th>Status</th>
        <th>Yetkisiz Bırak</th>
        <th>Yetkisini Değiştir</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.AdminID</th>
            <td>@item.AdminUsername</td>
            <td>@item.AdminRole</td>
            <td>Aktif</td>
            <td><a href="/Authorization/DeleteAdmin/@item.AdminID" class="btn btn-danger">Pasif Yap</a></td>
            <td><a href="/Authorization/AdminUpdate/@item.AdminID" class="btn btn-warning">Yetkisini Değiştir</a></td>
        </tr>
    }
</table>
<a href="/Authorization/AddAdmin" class="btn btn-info">Yeni Admin Tanımla</a>